---
- name: OS-Specific-installation
  hosts: all
  become: yes
  tasks:
    - name: install on redhat
      yum:
       name: httpd
       state: present
      when: ansible_os_family == "RedHat"
    - name: install apage on debian
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

