---
- name: Install multiple packages
  hosts: all
  become: yes
  vars:
    packages:
      - git
      - curl
      - tree
  tasks:
    - name: install-packages
      apt:
        name: "{{item}}"
      loop: "{{packages}}"
